name: Pingy
options:
  minimumXcodeGenVersion: 2.38.0
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: 5.9
    IPHONEOS_DEPLOYMENT_TARGET: 16.0
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    GENERATE_INFOPLIST_FILE: NO
    ENABLE_USER_SCRIPT_SANDBOXING: NO
packages: {}
targets:
  Pingy:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: Pingy
      - path: Resources
        buildPhase: resources
    settings:
      base:
        PRODUCT_NAME: Pingy
        PRODUCT_BUNDLE_IDENTIFIER: com.pingy.messenger
        INFOPLIST_FILE: Pingy/App/Info.plist
        CODE_SIGN_ENTITLEMENTS: Pingy/App/Pingy.entitlements
        DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM}
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 2.0
        TARGETED_DEVICE_FAMILY: 1,2
        SUPPORTED_PLATFORMS: iphoneos iphonesimulator
        SUPPORTS_MACCATALYST: NO
        UILaunchStoryboardName: LaunchScreen
    scheme:
      testTargets: []
